"""empty message

Revision ID: d3936f9df8ee
Revises: 1f1db338daec
Create Date: 2020-06-09 23:05:04.488403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3936f9df8ee'
down_revision = '1f1db338daec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors_table', 'movies',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors_table', 'movies',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
